### ISSUE TITLE
Vulnerability related to backup Data : beancount-mobile

### ISSUE THREAD

**Issue by Simran-cmd** [puncsky/beancount-mobile#14]
Hi, 
**Vulnerability 1** 
**Name** : Application Data can be Backed up
**Severity**  : High
**Vulnerable Parameter** : [android:allowBackup=true] 
**Description**  : This flag allows anyone to backup your application data via adb. It allows users who have enabled USB debugging to copy application data off of the device. 
**Steps to reproduce** : 
1. Debug the apk using apktool.
2. Go to AndroidManifest.xml
3. Search using any content finder for the given call : [android:allowBackup=true] 
**Supporting Material/References** : 
![backup](https://user-images.githubusercontent.com/63577507/96841554-8e82f200-1469-11eb-9799-0d348cbedae6.png)

**Impact** : If this attribute is set to true, backup or restore of the application can be easily performed, even by a full-system backup that would otherwise cause all application data to be saved via adb. 

**Vulnerability 2** 
**Name** : Clear text traffic is Enabled For App
**Severity** : High
**Vulnerable Parameter** : [android:usesCleartextTraffic=true] 
**Description** : The app intends to use cleartext network traffic, such as cleartext HTTP, FTP stacks, DownloadManager, and MediaPlayer. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false". The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.****
**Steps to reproduce** : 
1. Debug the apk using apktool.
2. Go to AndroidManifest.xml
3. Search using any content finder for the given call : [android:usesCleartextTraffic=true] 
**Supporting Material/References** : 
![clear text traffic](https://user-images.githubusercontent.com/63577507/96842357-8e372680-146a-11eb-827f-ea72527420e7.png)

**Impact** : Keeping This call as true could create accidental regressions in apps due to changes in URLs provided by external sources such as backend servers.

Thanks, 
Simran, India
Telegram - simranCMD

**Comment by puncsky** [comment]
thanks for reporting the issue to us and we will evaluate and get back to you after the evaluation of the vulnerabilities!

**Comment by yuyongmao** [comment]
These may be the default configuration of Androidmanifest.XML
Or expo do this

**Comment by puncsky** [comment]
> Hi, 
> 
> **Vulnerability 1** 
> 
> **Name** : Application Data can be Backed up
> 
> **Severity**  : High
> 
> **Vulnerable Parameter** : [android:allowBackup=true] 
> 
> **Description**  : This flag allows anyone to backup your application data via adb. It allows users who have enabled USB debugging to copy application data off of the device. 
> 
> **Steps to reproduce** : 
> 
> 1. Debug the apk using apktool.
> 
> 2. Go to AndroidManifest.xml
> 
> 3. Search using any content finder for the given call : [android:allowBackup=true] 
> 
> **Supporting Material/References** : 
> 
> ![backup](https://user-images.githubusercontent.com/63577507/96841554-8e82f200-1469-11eb-9799-0d348cbedae6.png)
> 
> 
> 
> **Impact** : If this attribute is set to true, backup or restore of the application can be easily performed, even by a full-system backup that would otherwise cause all application data to be saved via adb. 
> 
> 
> 
> 
> 
> **Vulnerability 2** 
> 
> **Name** : Clear text traffic is Enabled For App
> 
> **Severity** : High
> 
> **Vulnerable Parameter** : [android:usesCleartextTraffic=true] 
> 
> **Description** : The app intends to use cleartext network traffic, such as cleartext HTTP, FTP stacks, DownloadManager, and MediaPlayer. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false". The key reason for avoiding cleartext traffic is the lack of confidentiality, authenticity, and protections against tampering; a network attacker can eavesdrop on transmitted data and also modify it without being detected.****
> 
> **Steps to reproduce** : 
> 
> 1. Debug the apk using apktool.
> 
> 2. Go to AndroidManifest.xml
> 
> 3. Search using any content finder for the given call : [android:usesCleartextTraffic=true] 
> 
> **Supporting Material/References** : 
> 
> ![clear text traffic](https://user-images.githubusercontent.com/63577507/96842357-8e372680-146a-11eb-827f-ea72527420e7.png)
> 
> 
> 
> **Impact** : Keeping This call as true could create accidental regressions in apps due to changes in URLs provided by external sources such as backend servers.
> 
> 
> 
> Thanks, 
> 
> Simran, India
> 
> Telegram - simranCMD

Thanks again for helping us identify issues. Unfortunately, this layer of concern is take care of by the Expo. There is nothing we can do here. And I encourage you to report it in their communities 😃
