### ISSUE TITLE
Android Manifest Issues

### ISSUE THREAD

**Issue by mufaddalmasala** [puncsky/beancount-mobile#15]
### Vulnerability 1
**Name:** Activities are not protected
**Description:** An Activity is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. {android :exported= true}
**Activities:** 
_abi35_0_0.expo.modules.payments.stripe.RedirectUriReceiver
abi36_0_0.expo.modules.payments.stripe.RedirectUriReceiver
abi37_0_0.expo.modules.payments.stripe.RedirectUriReceiver
abi38_0_0.expo.modules.payments.stripe.RedirectUriReceiver
androidx.biometric.DeviceCredentialHandlerActivity
com.facebook.CustomTabActivity
expo.modules.payments.stripe.RedirectUriReceiver
host.exp.exponent.experience.TvActivity
host.exp.exponent.LauncherActivity
net.openid.appauth.RedirectUriReceiverActivity_
**Used Tools:** apktool
**File:** AndroidManifest.xml
**Impact:** Malicious application keeps calling the exported activities so that not logged in users are also impacted & it also leads to crash the app continuously
**Steps to Reproduce:** 
1. Decompile the apk using apktool
2. Command: apktool d [package_name]
3. cat AndroidManifest.xml | grep true
**References:**
https://cwe.mitre.org/data/definitions/926.html
https://hackerone.com/reports/65729
![activity not protected](https://user-images.githubusercontent.com/20786373/96872458-47a8f280-1491-11eb-9020-e9d594a97b45.png)
![exported](https://user-images.githubusercontent.com/20786373/96872462-48418900-1491-11eb-8deb-27ef90d749a6.png)

### Vulnerability 2
**Name:** Broadcast Receiver is Protected by a permission, but the protection level of the permission should be checked
**Description:** A Broadcast Receiver is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. It is protected by a permission which is not defined in the analysed application. As a result, the protection level of the permission should be checked where it is defined. If it is set to normal or dangerous, a malicious application can request and obtain the permission and interact with the component. If it is set to signature, only applications signed with the same certificate can obtain the permission. {android :exported= true}
**Broadcast Receivers:**
Broadcast Receiver: _com.facebook.CampaignTrackingReceiver_
Permission: _android.permission.INSTALL_PACKAGES_ 
Broadcast Receiver: _com.google.android.gms.gcm.GcmReceiver_
Permission: _com.google.android.c2dm.permission.SEND_ 
Broadcast Receiver: _com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver_
Permission: _android.permission.INSTALL_PACKAGES_ 
Broadcast Receiver: _com.google.firebase.iid.FirebaseInstanceIdReceiver_
Permission: _com.google.android.c2dm.permission.SEND_

Broadcast Receivers not protected:
_host.exp.exponent.notifications.receivers.SchedulingTriggerReceiver
host.exp.exponent.referrer.InstallReferrerReceiver_
**File:** AndroidManifest.xml
**Used Tools:** apktool
**Steps to Reproduce:** 
1. Decompile the apk using apktool
2. Command: apktool d [package_name]
3. cat AndroidManifest.xml | grep true
**References:**
https://cwe.mitre.org/data/definitions/926.html
![broadcast receiver exported](https://user-images.githubusercontent.com/20786373/96872485-542d4b00-1491-11eb-997c-2fae477652ee.png)

### Vulnerability 3
**Name:** A Service is Protected by a permission, but the protection level of the permission should be checked
**Description:** A Service is found to be shared with other apps on the device therefore leaving it accessible to any other application on the device. It is protected by a permission which is not defined in the analysed application. As a result, the protection level of the permission should be checked where it is defined. If it is set to normal or dangerous, a malicious application can request and obtain the permission and interact with the component. If it is set to signature, only applications signed with the same certificate can obtain the permission. {android :exported= true}
**Services:**
Service: _com.google.android.gms.auth.api.signin.RevocationBoundService_
Permission: _com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION_

Services not protected:
_host.exp.exponent.fcm.ExpoFcmMessagingService_
**File:** AndroidManifest.xml
**Used Tools:** apktool
**Steps to Reproduce:** 
1. Decompile the apk using apktool
2. Command: apktool d [package_name]
3. cat AndroidManifest.xml | grep true
**References:**
https://cwe.mitre.org/data/definitions/926.html
![service exported](https://user-images.githubusercontent.com/20786373/96872510-5abbc280-1491-11eb-886e-eaf171e767ae.png)

Regards,
Mufaddal M
India
Telegram: @muffynsta

**Comment by puncsky** [comment]
thanks for reporting the issue to us and we will evaluate and get back to you after the evaluation of the vulnerabilities!

**Comment by yuyongmao** [comment]
<img width="1112" alt="Screen Shot 2020-10-24 at 9 26 42 PM" src="https://user-images.githubusercontent.com/8936260/97082972-e2473400-163f-11eb-9d8e-29034738799a.png">

expo do this

**Comment by puncsky** [comment]
Thanks again for helping us identify issues. Unfortunately, this layer of concern is take care of by the Expo. There is nothing we can do here. And I encourage you to report it in their communities 😃
